apiVersion: v1
kind: Service
metadata:
  name: aegisrun-api
  namespace: aegisrun
  labels:
    app.kubernetes.io/name: aegisrun
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: aegisrun
    app.kubernetes.io/component: api
