apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegisrun

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"

images:
  - name: ghcr.io/aegisrun/aegisrun/api
    newTag: latest
  - name: ghcr.io/aegisrun/aegisrun/ui
    newTag: latest
