param(
    [Parameter(Mandatory = $true)]
    [string]$Version,

    [Parameter(Mandatory = $true)]
    [string]$ReleaseBranch
)

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "../..")).Path
$timestamp = (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
$safeVersion = $Version -replace '[^a-zA-Z0-9._-]', '_'
$outDir = Join-Path $repoRoot "artifacts/releases/$timestamp-$safeVersion"

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$checklistSrc = Join-Path $repoRoot 'docs/RELEASE_CHECKLIST.md'
$checklistDst = Join-Path $outDir 'release-checklist.md'
if (Test-Path $checklistSrc) {
    Copy-Item -Path $checklistSrc -Destination $checklistDst -Force
}

$evidenceFile = Join-Path $outDir 'release-evidence.md'
@"
# Release Evidence Pack

- Version: $Version
- Release Branch: $ReleaseBranch
- Generated At (UTC): $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))
- Generated By: prepare-release-evidence.ps1

---

## 1) Release-Gate Workflow (`release-gate.yml`)

- Run URL:
- Run ID:
- Triggered At (UTC):
- Completed At (UTC):
- Final Status:

### Required Jobs

| Job | Result | Notes |
|---|---|---|
| api-unit-tests | ☐ pass / ☐ fail | |
| verifier-tests | ☐ pass / ☐ fail | |
| python-sdk-tests | ☐ pass / ☐ fail | |
| typescript-sdk-tests | ☐ pass / ☐ fail | |
| ui-tests | ☐ pass / ☐ fail | |
| security-sbom | ☐ pass / ☐ fail | |
| security-provenance | ☐ pass / ☐ fail | |
| load-test | ☐ pass / ☐ fail | |
| canary-health-gate | ☐ pass / ☐ fail | |
| ops-drill-cadence | ☐ pass / ☐ fail | |
| slo-escalation-gate | ☐ pass / ☐ fail | |
| release-gate-verdict | ☐ pass / ☐ fail | |

### Required Artifacts

| Artifact | Present | Link |
|---|---|---|
| sbom-release-gate | ☐ yes / ☐ no | |
| load-test-results | ☐ yes / ☐ no | |

---

## 2) Tag Release Workflow (`release.yml`)

- Run URL:
- Run ID:
- Triggered At (UTC):
- Completed At (UTC):
- Final Status:

### Required Jobs

| Job | Result | Notes |
|---|---|---|
| release-security-gate | ☐ pass / ☐ fail | |
| release-sbom | ☐ pass / ☐ fail | |
| build-and-push | ☐ pass / ☐ fail | |
| publish-python-sdk | ☐ pass / ☐ fail | |
| publish-typescript-sdk | ☐ pass / ☐ fail | |
| create-release | ☐ pass / ☐ fail | |

### Required Artifacts

| Artifact | Present | Link |
|---|---|---|
| release-sbom | ☐ yes / ☐ no | |
| release binaries (verifier) | ☐ yes / ☐ no | |

---

## 3) Provenance / Attestation Records

| Subject | Attestation Link | Digest / Subject |
|---|---|---|
| API image | | |
| UI image | | |
| Verifier image | | |
| Python SDK artifacts | | |
| TypeScript SDK package | | |

---

## 4) Final Sign-Off Summary

- Release checklist path: `./release-checklist.md`
- Readiness score (must be >= 90):
- Release Manager approval:
- Engineering Lead approval:
- Security Lead approval:
- Final Decision: ☐ GO / ☐ NO-GO
"@ | Out-File -FilePath $evidenceFile -Encoding utf8

Write-Output "Release evidence pack prepared."
Write-Output "Directory: $outDir"
Write-Output "Evidence file: $evidenceFile"
Write-Output "Checklist copy: $checklistDst"
